//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI642_BonoCorporativo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Transaction = new HashSet<Transaction>();
        }

        public int Id { get; set; }
        [Display(Name = "Nombres")]
        [Required(ErrorMessage = "Error: Debe ingresar el campo Nombres")]
        //[RegularExpression(@"[a-zA-ZñÑ\s]", ErrorMessage = "Error: Solo Texto")]
        public string Name { get; set; }
        [Display(Name = "Apellido Paterno")]
        [Required(ErrorMessage = "Error: Debe ingresar el campo Apellido Paterno")]
        //[RegularExpression(@"[a-zA-ZñÑ\s]", ErrorMessage = "Error: Solo Texto")]
        public string FatherLastName { get; set; }
        [Display(Name = "Apellido Materno")]
        [Required(ErrorMessage = "Error: Debe ingresar el campo Apellido Materno")]
        //[RegularExpression(@"[a-zA-ZñÑ\s]", ErrorMessage = "Error: Solo Texto")]
        public string MotherLastName { get; set; }
        [Display(Name = "DNI")]
        [Required(ErrorMessage = "Error: Debe ingresar el campo DNI")]
        [StringLength(8, MinimumLength = 8, ErrorMessage = "Error: Solo 8 Digitos")]
        [RegularExpression(@"[0-9]{1,9}(\.[0-9]{0,2})?$", ErrorMessage = "Error: Solo Números")]
        public string DNI { get; set; }
        [Display(Name = "Contraseña")]
        [Required(ErrorMessage = "Error: Debe ingresar el campo Contraseña")]
        public string Password { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transaction { get; set; }
    }
}
